# Spark metric properties file
# For details, refer to conf/metrics.properties.template

# This is a MDM account set up for MT Spark MDM publishing 
# *.sink.mdm.class=org.apache.spark.metrics.sink.MdmSink
# *.sink.mdm.period=5
# *.sink.mdm.unit=MINUTES
# *.sink.mdm.monitoringAccount=MyJarvisAccount

# Report only metrics whose names match the following pattern. E.g. using the pattern
# "^(?!executor\\.filesystem\\.|HiveExternalCatalog\\.).*$" all metrics will be reported except
# those whose names begin with "executor.filesystem." or "HiveExternalCatalog.".
# *.sink.mdm.metricPattern=^(?!executor\\.filesystem\\.|executor\\.threadpool\\.|HiveExternalCatalog\\.).*$

# Enable JvmSource for instance driver and executor
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource
