# Spark metric properties file
# For details, refer to conf/metrics.properties.template

# This is a MDM account set up for MT Spark MDM publishing 
*.sink.mdm.class=org.apache.spark.metrics.sink.MdmSink
*.sink.mdm.period=1
*.sink.mdm.unit=MINUTES
*.sink.mdm.monitoringAccount=mtspark
